language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
notifications:
  slack:
    secure: ju4T/ovhqdyLtmlkatygNwEg4QBB+OfSpbnFJclTkChipNhsmL06otI6sFqccH445LcV8blQ4XOAnPEgAmk89aIXTPUhZMT+D5j3ZQDyHSQPJ8ejr4yFC98xMbnxzjzptTvLyBz4raIVUuUHe4DV/pujgWa+kedknG3NOT47y/em6I6LW7GdYVfFQxqYi3mqMeSfWDjqsKc12NYzEtSaZvl7LhlsigZXGIUPKgRkvijGXj4OXbrIXmcleCCCSEBsiLRhBFH01IAufhZR7gCTuCE456TsFtFdjKuYUdqanbBkHS3LkVilgkeB2oJxQkobDoXhEkLZrSHBQ99C9/ZZBEGSm7XUOKf/vMSQxCmT3xV33P8UuGOfqc0cuPaM4PihHyKuc1H04fjmx63/czhkAJL1nqM+xgkPJNQDeR3Kz0tZDvalky35vjmSb3P2H/g+FPaIdW994ft9A2C8aNXt6EBrtcZvfErjAFxedZhsEh0NDGZc5mPGgH6K1stmotcdjsm7voXP813eOARDauhM6IfTxGgS6LWJr9UUVuylfUT5VVYLMrYcasSSPo1HfgPbHMXKp6wJxD9T4AuLPXVzEqznkJT/25tjx/59VPx/qqgXI1z37NU/jnli5gtnHQODwqSXDKmfQp/9mZF2ZwOVQ08bdoRwGLh119YTzuMt+pU=
